name: Build and Deploy Online Documentation

on:
  # Trigger the workflow on push request,
  # for the dev branch
  push:
    branches:
      - 'dev'
    paths:
     - 'docs/**'
     - 'lmcache/**'
     - 'examples/**'
jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # for setuptools-scm
          fetch-depth: 0

      - name: Setup Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/docs.txt

      - name: Build Sphinx Documentation
        run: |
          sphinx-build docs/source output
        continue-on-error: false

      - name: Add .nojekyll
        run: |
          touch output/.nojekyll

      - name: Upload doc artifacts to GHA
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: doc-artifacts
          path: output/

  deploy-docs:
    name: Deploy docs online
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Fetch doc artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
            name: doc-artifacts
            path: output

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: LM-Cache-Website/lm-cache-website.github.io
          token: ${{ secrets.LMCACHE_DOC }}
          path: target-repo

      - name: Copy Files to Target Repository
        run: |
          cp -r output/* target-repo/

      - name: Commit and Push to Target Repository
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Deploy updated online docs"
            git push https://x-access-token:${{ secrets.LMCACHE_DOC }}@github.com/LM-Cache-Website/lm-cache-website.github.io.git main --force
          else
            echo "No changes to commit."
          fi
